import { CalculatorConfig } from '../types/calculator';

export const calculator: CalculatorConfig = {
    slug: 'compound-interest',
    name: 'Compound Interest Calculator',
    category: 'investing',
    metaTitle: 'Compound Interest Calculator - Plot Exponential Growth',
    metaDesc: 'Discover the power of compound interest. Plot beautiful growth curves and see how different compounding frequencies alter returns.',
    primaryKeyword: 'Compound Interest Calculator',
    formulaName: 'Compound Interest Formula',
    formulaDesc: 'A = P × (1 + r/n)^(n·t).',
    explanation: 'Compound interest is the addition of interest to the principal sum of a loan or deposit, or in other words, interest on interest. It is the core motor of all wealth generation.',
    example: 'A principal of $10,000 compounding annually at 10% interest for 20 years results in a total future value of $67,275.',
    relatedSlugs: ['investment', 'future-value', 'rule-of-72', 'savings-goal'],
    fields: [
      { key: 'principal', label: 'Initial Principal (P)', type: 'number', defaultValue: 10000, isCurrency: true },
      { key: 'contribution', label: 'Monthly Addition (PMT)', type: 'number', defaultValue: 300, isCurrency: true },
      { key: 'years', label: 'Timeline in Years (t)', type: 'number', defaultValue: 15, min: 1, max: 50 },
      { key: 'rate', label: 'Annual Interest Rate (r, %)', type: 'number', defaultValue: 10, isPercent: true },
    ],
    faqs: [
      { question: 'What is compound frequency?', answer: 'How often interest is calculated and added to the principal (e.g., daily, monthly, quarterly, or annually). More frequent compounding slightly expands long-term yields.' },
      { question: 'What is the "Snowball Effect"?', answer: 'In early years, compound growth feels slow. However, after 10-15 years, the interest earned begins to dwarf your physical savings contribution, causing the balance to shoot upward.' }
    ],
    calculate: (inputs, currency) => {
      const p = inputs.principal || 0;
      const pmt = inputs.contribution || 0;
      const t = inputs.years || 15;
      const r = (inputs.rate || 10) / 100;

      let balance = p;
      let totalContributions = p;
      const chartData = [];

      for (let y = 1; y <= t; y++) {
        for (let m = 0; m < 12; m++) {
          balance = balance * (1 + r / 12) + pmt;
          totalContributions += pmt;
        }
        chartData.push({
          year: `Yr ${y}`,
          balance: Math.round(balance),
          contributions: Math.round(totalContributions),
        });
      }

      return {
        metrics: [
          { label: 'Future Portfolio Value', value: balance, isPrimary: true, desc: 'Accumulated balance' },
          { label: 'Total Contributions', value: totalContributions, desc: 'Sum of active manual deposits' },
          { label: 'Total Interest Earned', value: Math.max(0, balance - totalContributions), desc: 'Capital generated by compound growth' },
        ],
        chartData,
        explanationText: `Your initial principal and active additions compound into a total future sum of ${balance.toLocaleString()} over ${t} years. Interest generated constitutes ${Math.round((1 - (totalContributions/balance)) * 100)}% of your final portfolio.`
      };
    }
  };
