import { CalculatorConfig } from '../types/calculator';

export const INVESTING_CALCULATORS: CalculatorConfig[] = [
  {
    slug: 'compound-interest',
    name: 'Compound Interest Calculator',
    category: 'investing',
    metaTitle: 'Compound Interest Calculator - Plot Exponential Growth',
    metaDesc: 'Discover the power of compound interest. Plot beautiful growth curves and see how different compounding frequencies alter returns.',
    primaryKeyword: 'Compound Interest Calculator',
    formulaName: 'Compound Interest Formula',
    formulaDesc: 'A = P × (1 + r/n)^(n·t).',
    explanation: 'Compound interest is the addition of interest to the principal sum of a loan or deposit, or in other words, interest on interest. It is the core motor of all wealth generation.',
    example: 'A principal of $10,000 compounding annually at 10% interest for 20 years results in a total future value of $67,275.',
    relatedSlugs: ['investment', 'future-value', 'rule-of-72', 'savings-goal'],
    fields: [
      { key: 'principal', label: 'Initial Principal (P)', type: 'number', defaultValue: 10000, isCurrency: true },
      { key: 'contribution', label: 'Monthly Addition (PMT)', type: 'number', defaultValue: 300, isCurrency: true },
      { key: 'years', label: 'Timeline in Years (t)', type: 'number', defaultValue: 15, min: 1, max: 50 },
      { key: 'rate', label: 'Annual Interest Rate (r, %)', type: 'number', defaultValue: 10, isPercent: true },
    ],
    faqs: [
      { question: 'What is compound frequency?', answer: 'How often interest is calculated and added to the principal (e.g., daily, monthly, quarterly, or annually). More frequent compounding slightly expands long-term yields.' },
      { question: 'What is the "Snowball Effect"?', answer: 'In early years, compound growth feels slow. However, after 10-15 years, the interest earned begins to dwarf your physical savings contribution, causing the balance to shoot upward.' }
    ],
    calculate: (inputs, currency) => {
      const p = inputs.principal || 0;
      const pmt = inputs.contribution || 0;
      const t = inputs.years || 15;
      const r = (inputs.rate || 10) / 100;

      let balance = p;
      let totalContributions = p;
      const chartData = [];

      for (let y = 1; y <= t; y++) {
        for (let m = 0; m < 12; m++) {
          balance = balance * (1 + r / 12) + pmt;
          totalContributions += pmt;
        }
        chartData.push({
          year: `Yr ${y}`,
          balance: Math.round(balance),
          contributions: Math.round(totalContributions),
        });
      }

      return {
        metrics: [
          { label: 'Future Portfolio Value', value: balance, isPrimary: true, desc: 'Accumulated balance' },
          { label: 'Total Contributions', value: totalContributions, desc: 'Sum of active manual deposits' },
          { label: 'Total Interest Earned', value: Math.max(0, balance - totalContributions), desc: 'Capital generated by compound growth' },
        ],
        chartData,
        explanationText: `Your initial principal and active additions compound into a total future sum of ${balance.toLocaleString()} over ${t} years. Interest generated constitutes ${Math.round((1 - (totalContributions/balance)) * 100)}% of your final portfolio.`
      };
    }
  },
  {
    slug: 'investment',
    name: 'Investment Calculator',
    category: 'investing',
    metaTitle: 'Investment Calculator - Map Out Portfolio Projections',
    metaDesc: 'Simulate financial portfolio return rates over long-term timelines to structure custom asset goals.',
    primaryKeyword: 'Investment Calculator',
    formulaName: 'Investment Growth Modeling',
    formulaDesc: 'Portfolio Value = Principal × (1 + Return Rate)^t.',
    explanation: 'A general-purpose investment planning layout for examining how lump sums grow over time under variable interest returns.',
    example: 'A $25,000 index fund bundle growing at an 11% average annual yield expands to $148,450 over a 17-year timeline.',
    relatedSlugs: ['compound-interest', 'investment-return', 'future-value', 'portfolio-allocation'],
    fields: [
      { key: 'lumpSum', label: 'Initial Lump Sum', type: 'number', defaultValue: 25000, isCurrency: true },
      { key: 'annualAdd', label: 'Annual Contributions', type: 'number', defaultValue: 5000, isCurrency: true },
      { key: 'years', label: 'Investment Horizon (Years)', type: 'number', defaultValue: 20, min: 1, max: 40 },
      { key: 'returnRate', label: 'Expected Yield (%)', type: 'number', defaultValue: 9.5, isPercent: true },
    ],
    faqs: [
      { question: 'What expected return should I model?', answer: 'US and Indian broad-market indexes have historically achieved 10% to 13% average annual returns before inflation over multi-decade periods.' },
      { question: 'How do index funds simplify investing?', answer: 'They bundle hundreds of top companies into a single cheap basket, providing automatic diversification and matching overall market momentum.' }
    ],
    calculate: (inputs, currency) => {
      const lump = inputs.lumpSum || 0;
      const add = inputs.annualAdd || 0;
      const t = inputs.years || 20;
      const r = (inputs.returnRate || 9.5) / 100;

      let portfolio = lump;
      let contributions = lump;
      const chartData = [];

      for (let y = 1; y <= t; y++) {
        portfolio = portfolio * (1 + r) + add;
        contributions += add;
        chartData.push({
          year: `Yr ${y}`,
          portfolio: Math.round(portfolio),
          contributions: Math.round(contributions),
        });
      }

      return {
        metrics: [
          { label: 'Projected Portfolio', value: portfolio, isPrimary: true, desc: 'Compounded asset total' },
          { label: 'Your Active Capital', value: contributions, desc: 'Lump sum plus annual deposits' },
          { label: 'Total Growth Yield', value: Math.max(0, portfolio - contributions), desc: 'Market compound gains' },
        ],
        chartData,
        explanationText: `Sustaining your regular allocation yields a future investment bundle of ${portfolio.toLocaleString()} in ${t} years.`
      };
    }
  },
  {
    slug: 'passive-income',
    name: 'Passive Income Calculator',
    category: 'investing',
    metaTitle: 'Passive Income Calculator - Model Dividend & Cash Flows',
    metaDesc: 'Project long-term passive cash flows from dividend portfolios, fixed income vaults, and real estate allocations.',
    primaryKeyword: 'Passive Income Calculator',
    formulaName: 'Passive Yield Flow Formula',
    formulaDesc: 'Annual Passive Income = Total Portfolio Corpus × Average Annual Dividend Yield (%).',
    explanation: 'Passive income represents money earned with minimal active labor. This calculator helps you determine the capital corpus required to generate your dream monthly income.',
    example: 'To secure $2,000 per month ($24,000/year) in passive cash flow at a 5% average yield, you must build a portfolio of $480,000.',
    relatedSlugs: ['financial-freedom', 'retirement-income', 'compound-interest', 'investment-return'],
    fields: [
      { key: 'targetPassiveMonthly', label: 'Desired Monthly Passive Cash', type: 'number', defaultValue: 2500, isCurrency: true },
      { key: 'yieldPercent', label: 'Expected Asset Yield (Annual, %)', type: 'number', defaultValue: 5, min: 1, max: 15, isPercent: true },
      { key: 'currentCorpus', label: 'Current Yield-Bearing Capital', type: 'number', defaultValue: 30000, isCurrency: true },
    ],
    faqs: [
      { question: 'What are authentic passive income sources?', answer: 'Low-cost broad market indices, dividend growth ETFs, sovereign treasury bonds, high-yield deposit certificates, and real estate investment trusts (REITs).' },
      { question: 'Is 100% passive income realistic?', answer: 'Yes, but it requires accumulating a robust equity or asset base first. Compounding is the initial engine that makes true passive cash possible.' }
    ],
    calculate: (inputs, currency) => {
      const desiredMonthly = inputs.targetPassiveMonthly || 2500;
      const rate = (inputs.yieldPercent || 5) / 100;
      const cur = inputs.currentCorpus || 0;

      const annualNeeded = desiredMonthly * 12;
      const corpusRequired = annualNeeded / rate;
      const currentPassiveMonthly = (cur * rate) / 12;
      const gap = Math.max(0, corpusRequired - cur);

      const chartData = [
        { name: 'Current Capital', value: cur },
        { name: 'Target Capital Needed', value: corpusRequired },
      ];

      return {
        metrics: [
          { label: 'Required Capital Corpus', value: corpusRequired, isPrimary: true, desc: 'Corpus needed to support payout' },
          { label: 'Current Passive Flow', value: currentPassiveMonthly, desc: 'Passive yield you make today' },
          { label: 'Remaining Capital Gap', value: gap, desc: 'Additional capital to secure' },
        ],
        chartData,
        explanationText: `To harvest ${desiredMonthly.toLocaleString()} every month passively at a ${inputs.yieldPercent}% rate, you need an asset base of ${corpusRequired.toLocaleString()}. Your current assets produce ${currentPassiveMonthly.toLocaleString()} per month.`
      };
    }
  },
  {
    slug: 'future-value',
    name: 'Future Value Calculator',
    category: 'investing',
    metaTitle: 'Future Value Calculator - Calculate Compounded Worth',
    metaDesc: 'Project the future value of a single initial principal deposit with added continuous compounding yield.',
    primaryKeyword: 'Future Value Calculator',
    formulaName: 'Single Payment Future Value Formula',
    formulaDesc: 'FV = PV × (1 + r)^t.',
    explanation: 'Calculates how much a single lump sum of money invested today will be worth in the future under a constant compounding interest rate.',
    example: 'An initial investment of $10,000 held for 25 years at an 8% compounding yield expands to $68,485.',
    relatedSlugs: ['present-value', 'compound-interest', 'inflation', 'investment-return'],
    fields: [
      { key: 'presentVal', label: 'Present Lump Sum (PV)', type: 'number', defaultValue: 10000, isCurrency: true },
      { key: 'years', label: 'Horizon Timeline (Years)', type: 'number', defaultValue: 25, min: 1, max: 50 },
      { key: 'annualRate', label: 'Annual Compound Interest (%)', type: 'number', defaultValue: 8, isPercent: true },
    ],
    faqs: [
      { question: 'What is the Time Value of Money?', answer: 'The concept that money available today is worth more than the same amount in the future, due to its potential earning capacity.' },
      { question: 'How does tax affect Future Value?', answer: 'Taxes on dividends and capital gains drag down your effective annual returns. Using tax-advantaged retirement accounts can shield your compound gains.' }
    ],
    calculate: (inputs, currency) => {
      const pv = inputs.presentVal || 10000;
      const t = inputs.years || 25;
      const r = (inputs.annualRate || 8) / 100;

      const fv = pv * Math.pow(1 + r, t);
      const chartData = [];
      for (let i = 1; i <= t; i++) {
        chartData.push({
          year: `Yr ${i}`,
          value: Math.round(pv * Math.pow(1 + r, i)),
        });
      }

      return {
        metrics: [
          { label: 'Future Value (FV)', value: fv, isPrimary: true, desc: 'Total compounded value' },
          { label: 'Initial Principal', value: pv, desc: 'Your starting investment' },
          { label: 'Compound Gains', value: fv - pv, desc: 'Interest yield accrued' },
        ],
        chartData,
        explanationText: `Your initial lump sum grows to ${fv.toLocaleString()} over ${t} years under an 8% annual compound model.`
      };
    }
  },
  {
    slug: 'present-value',
    name: 'Present Value Calculator',
    category: 'investing',
    metaTitle: 'Present Value Calculator - Value Future Cash Flows Today',
    metaDesc: 'Determine the current value of a specific future lump sum payment using a custom discount interest rate.',
    primaryKeyword: 'Present Value Calculator',
    formulaName: 'Present Value Discount Formula',
    formulaDesc: 'PV = FV / (1 + r)^t.',
    explanation: 'Determines what a future lump sum of money is worth today, given a specific rate of return (known as the discount rate or hurdle rate).',
    example: 'To secure a payout of $100,000 in 15 years assuming an 8% hurdle rate, you must invest $31,524 today.',
    relatedSlugs: ['future-value', 'inflation', 'withdrawing-rate', 'compound-interest'],
    fields: [
      { key: 'futureValue', label: 'Desired Future Sum (FV)', type: 'number', defaultValue: 100000, isCurrency: true },
      { key: 'years', label: 'Timeline in Years (t)', type: 'number', defaultValue: 15, min: 1, max: 50 },
      { key: 'discountRate', label: 'Discount / Hurdle Rate (%)', type: 'number', defaultValue: 8, isPercent: true },
    ],
    faqs: [
      { question: 'What is a Discount Rate?', answer: 'The interest rate used to discount future cash flows back to their present value, representing your expected rate of return or alternative investment yield.' },
      { question: 'Why is Present Value useful?', answer: 'It helps you compare different investment options. If a project promises a future payoff, you can discount it back to see if its present value justifies the cost today.' }
    ],
    calculate: (inputs, currency) => {
      const fv = inputs.futureValue || 100000;
      const t = inputs.years || 15;
      const r = (inputs.discountRate || 8) / 100;

      const pv = fv / Math.pow(1 + r, t);
      const chartData = [];
      for (let i = t; i >= 1; i--) {
        chartData.push({
          year: `Yr ${t - i + 1}`,
          presentWorth: Math.round(fv / Math.pow(1 + r, i)),
        });
      }

      return {
        metrics: [
          { label: 'Present Value (PV)', value: pv, isPrimary: true, desc: 'What you need to invest today' },
          { label: 'Desired Future Value', value: fv, desc: 'Target payoff size' },
          { label: 'Discount Subsidies', value: fv - pv, desc: 'Compounding growth leverage' },
        ],
        chartData,
        explanationText: `To secure a future payout of ${fv.toLocaleString()} in ${t} years at an 8% yield, you need to invest ${pv.toLocaleString()} today.`
      };
    }
  },
  {
    slug: 'rule-of-72',
    name: 'Rule of 72 Calculator',
    category: 'investing',
    metaTitle: 'Rule of 72 Calculator - Estimate Doubling Timelines',
    metaDesc: 'A fast mental shorthand formula to estimate how many years it takes to double your investment capital at any interest yield.',
    primaryKeyword: 'Rule of 72 Calculator',
    formulaName: 'The Doubling Shortcut Rule',
    formulaDesc: 'Years to Double = 72 / Annual Return Rate (%).',
    explanation: 'The Rule of 72 is an incredibly simple mathematical shortcut used to determine how long it takes for an investment to double in value under a constant annual rate of compound interest.',
    example: 'At a 9% annual broad-market index return, your capital doubles approximately every 72 / 9 = 8 years.',
    relatedSlugs: ['compound-interest', 'future-value', 'investment-return', 'savings-goal'],
    fields: [
      { key: 'annualYield', label: 'Expected Return Rate (%)', type: 'number', defaultValue: 9, min: 1, max: 30, isPercent: true },
      { key: 'principal', label: 'Starting Principal (Optional)', type: 'number', defaultValue: 10000, isCurrency: true },
    ],
    faqs: [
      { question: 'Is the Rule of 72 mathematically exact?', answer: 'No, it is a highly accurate mental approximation. The exact formula is ln(2)/ln(1+r), which yields 7.27 years for 10% returns, while the Rule of 72 yields 7.2 years.' },
      { question: 'What is the Rule of 114 and Rule of 144?', answer: 'Similar shortcuts: 114 / return rate estimates the years to triple your capital, and 144 / return rate estimates years to quadruple it.' }
    ],
    calculate: (inputs, currency) => {
      const r = inputs.annualYield || 9;
      const p = inputs.principal || 10000;

      const yearsToDouble = 72 / r;
      const chartData = [
        { name: 'Start', value: p },
        { name: 'Double Target', value: p * 2 },
      ];

      return {
        metrics: [
          { label: 'Years to Double', value: `${yearsToDouble.toFixed(1)} years`, isPrimary: true, desc: 'Time for capital to double' },
          { label: 'Value after Doubling', value: p * 2, desc: 'Doubled portfolio cushion' },
          { label: 'Estimated Years to Quadruple', value: `${(yearsToDouble * 2).toFixed(1)} years`, desc: 'Time to grow 4x (Rule of 144)' },
        ],
        chartData,
        explanationText: `At a constant ${r}% annual yield, any investment principal will double in size approximately every ${yearsToDouble.toFixed(1)} years.`
      };
    }
  },
  {
    slug: 'investment-return',
    name: 'Investment Return Calculator',
    category: 'investing',
    metaTitle: 'Investment Return Calculator - Calculate ROI & CAGR',
    metaDesc: 'Measure your actual compound annual growth rate (CAGR) and total return on investment (ROI) for any asset bundle.',
    primaryKeyword: 'Investment Return Calculator',
    formulaName: 'Compound Annual Growth Rate (CAGR)',
    formulaDesc: 'CAGR = (Ending Value / Starting Value)^(1 / Years) - 1.',
    explanation: 'Calculates the year-over-year growth rate of an investment over a multi-year period, representing the steady return rate as if it compounded smoothly.',
    example: 'An investment that grew from $10,000 to $25,000 over 7 years achieved a CAGR of 13.98% and a total ROI of 150%.',
    relatedSlugs: ['compound-interest', 'investment', 'rule-of-72', 'portfolio-allocation'],
    fields: [
      { key: 'startingValue', label: 'Starting Capital Value', type: 'number', defaultValue: 10000, isCurrency: true },
      { key: 'endingValue', label: 'Current / Ending Value', type: 'number', defaultValue: 25000, isCurrency: true },
      { key: 'years', label: 'Timeline in Years', type: 'number', defaultValue: 7, min: 1, max: 40 },
    ],
    faqs: [
      { question: 'What is the difference between CAGR and simple ROI?', answer: 'ROI measures your total return from start to finish (e.g., a 100% gain). CAGR factors in the time value of money, showing what annual compound interest rate was required to produce that gain.' },
      { question: 'Why is CAGR preferred for comparing assets?', answer: 'Because it annualizes gains, letting you compare a 3-year equity trade directly against a 10-year real estate investment on equal terms.' }
    ],
    calculate: (inputs, currency) => {
      const start = inputs.startingValue || 10000;
      const end = inputs.endingValue || 25000;
      const y = inputs.years || 7;

      const totalGain = Math.max(0, end - start);
      const roi = (totalGain / start) * 100;
      const cagr = (Math.pow(end / start, 1 / y) - 1) * 100;

      const chartData = [
        { name: 'Initial Capital', value: start },
        { name: 'Ending Value', value: end },
      ];

      return {
        metrics: [
          { label: 'CAGR (Annualized)', value: `${cagr.toFixed(2)}%`, isPrimary: true, desc: 'Compound Annual Growth Rate' },
          { label: 'Total ROI (%)', value: `${roi.toFixed(1)}%`, desc: 'Return on Investment ratio' },
          { label: 'Absolute Cash Gains', value: totalGain, desc: 'Value expansion in cash' },
        ],
        chartData,
        explanationText: `Your investment generated an annualized CAGR of ${cagr.toFixed(2)}%, multiplying your principal by ${(end/start).toFixed(2)}x in ${y} years.`
      };
    }
  },
  {
    slug: 'portfolio-allocation',
    name: 'Portfolio Allocation Calculator',
    category: 'investing',
    metaTitle: 'Portfolio Allocation Calculator - Asset Diversity Planner',
    metaDesc: 'Design your target asset allocation based on your current age, risk tolerances, and compound growth objectives.',
    primaryKeyword: 'Portfolio Allocation Calculator',
    formulaName: 'The Rule of 110/120',
    formulaDesc: 'Equity Allocation (%) = 110 (or 120) - Your Current Age.',
    explanation: 'Asset allocation determines over 90% of your portfolio\'s long-term return volatility. This planner builds a custom target layout of equities, fixed income, and cash based on your risk profile.',
    example: 'For a 30-year-old with a moderate risk appetite, the 110-age rule suggests an allocation of 80% equities, 15% bonds, and 5% cash.',
    relatedSlugs: ['investment', 'compound-interest', 'withdrawal-rate', 'net-worth'],
    fields: [
      { key: 'currentAge', label: 'Current Age', type: 'number', defaultValue: 30, min: 15, max: 80 },
      { key: 'riskAppetite', label: 'Risk Tolerance', type: 'select', defaultValue: 'moderate', options: [
        { label: 'Conservative (Low Volatility)', value: 'conservative' },
        { label: 'Moderate (Balanced Growth)', value: 'moderate' },
        { label: 'Aggressive (Maximum Compounding)', value: 'aggressive' },
      ]},
    ],
    faqs: [
      { question: 'Why is asset allocation critical?', answer: 'Different asset classes react differently to market events. Equities provide high growth, bonds cushion drawdowns, and cash ensures liquidity. A balanced allocation protects your net worth.' },
      { question: 'What is Portfolio Rebalancing?', answer: 'The practice of selling high-growth assets to buy underperforming ones once a year, keeping your portfolio aligned with your target risk profile.' }
    ],
    calculate: (inputs, currency) => {
      const age = inputs.currentAge || 30;
      const risk = inputs.riskAppetite || 'moderate';

      let equities = 0;
      if (risk === 'aggressive') {
        equities = Math.max(40, 120 - age);
      } else if (risk === 'conservative') {
        equities = Math.max(20, 90 - age);
      } else {
        equities = Math.max(30, 110 - age);
      }

      const remaining = 100 - equities;
      const fixedIncome = Math.round(remaining * 0.75);
      const cash = 100 - equities - fixedIncome;

      const chartData = [
        { name: 'Equities (Growth)', value: equities },
        { name: 'Fixed Income (Defense)', value: fixedIncome },
        { name: 'Cash / Buffer (Liquidity)', value: cash },
      ];

      return {
        metrics: [
          { label: 'Target Equities (%)', value: `${equities}%`, isPrimary: true, desc: 'Stocks & Index Funds allocation' },
          { label: 'Target Bonds (%)', value: `${fixedIncome}%`, desc: 'Fixed income & Debt allocation' },
          { label: 'Target Cash (%)', value: `${cash}%`, desc: 'Emergency cash & HYSA allocation' },
        ],
        chartData,
        explanationText: `Based on your age (${age}) and a ${risk} risk appetite, our model suggests a growth-forward allocation of ${equities}% equities, ${fixedIncome}% bonds, and ${cash}% cash.`
      };
    }
  },
  {
    slug: 'expense-ratio',
    name: 'Expense Ratio Calculator',
    category: 'investing',
    metaTitle: 'Expense Ratio Calculator - Audit Mutual Fund Cost Drag',
    metaDesc: 'Examine how fund management fees and expense ratios drag down your portfolio worth over long horizons.',
    primaryKeyword: 'Expense Ratio Calculator',
    formulaName: 'Annual Fee Impact Formula',
    formulaDesc: 'Portfolio Outflow = Average Balance × Expense Ratio (%).',
    explanation: 'Calculates the long-term impact of asset management fees (expense ratios) on your investment returns. Even minor fee differences (e.g., 0.1% vs 1.2%) can consume hundreds of thousands of dollars over decades.',
    example: 'Investing $100,000 for 30 years at 9% return with a 0.1% expense ratio yields $1,283,299. If the fee is 1.25%, your final balance drops to $915,227—costing you $368,072 in lost gains.',
    relatedSlugs: ['compound-interest', 'investment', 'withdrawal-rate', 'present-value'],
    fields: [
      { key: 'portfolioSize', label: 'Starting Portfolio Size', type: 'number', defaultValue: 100000, isCurrency: true },
      { key: 'annualContribution', label: 'Annual Savings Contribution', type: 'number', defaultValue: 10000, isCurrency: true },
      { key: 'years', label: 'Timeline in Years', type: 'number', defaultValue: 25, min: 1, max: 40 },
      { key: 'expectedReturn', label: 'Expected Gross Return (%)', type: 'number', defaultValue: 9, isPercent: true },
      { key: 'expenseRatio', label: 'Fund Expense Ratio (%)', type: 'number', defaultValue: 1.15, min: 0.05, max: 3, step: 0.05, isPercent: true },
    ],
    faqs: [
      { question: 'What is a mutual fund Expense Ratio?', answer: 'An annual fee charged by mutual funds or ETFs to cover portfolio management, administration, and marketing, expressed as a percentage of your total asset balance.' },
      { question: 'What is a cheap expense ratio?', answer: 'Broad market index funds from providers like Vanguard, Fidelity, or top Indian AMC index plans usually cost between 0.03% and 0.20% per year.' }
    ],
    calculate: (inputs, currency) => {
      const p = inputs.portfolioSize || 100000;
      const add = inputs.annualContribution || 10000;
      const t = inputs.years || 25;
      const gross = (inputs.expectedReturn || 9) / 100;
      const fee = (inputs.expenseRatio || 1.15) / 100;

      const netReturn = gross - fee;

      let pGross = p;
      let pNet = p;
      const chartData = [];

      for (let y = 1; y <= t; y++) {
        pGross = pGross * (1 + gross) + add;
        pNet = pNet * (1 + netReturn) + add;
        chartData.push({
          year: `Yr ${y}`,
          grossValue: Math.round(pGross),
          netValue: Math.round(pNet),
        });
      }

      const totalFeesPaid = pGross - pNet;

      return {
        metrics: [
          { label: 'Lost to Management Fees', value: totalFeesPaid, isPrimary: true, desc: 'Compounded fee drag cost' },
          { label: 'Fund Balance (Net of Fees)', value: pNet, desc: 'What you keep' },
          { label: 'Full Balance (No Fees)', value: pGross, desc: 'Ideal fee-free balance' },
        ],
        chartData,
        explanationText: `A management fee of ${inputs.expenseRatio}% drags your final balance down by ${totalFeesPaid.toLocaleString()} over ${t} years, consuming ${Math.round((totalFeesPaid/pGross)*100)}% of your potential gross portfolio value.`
      };
    }
  }
];
