import { CalculatorConfig } from '../types/calculator';

export const calculator: CalculatorConfig = {
    slug: 'portfolio-growth',
    name: 'Portfolio Growth Calculator',
    category: 'investing',
    metaTitle: 'Portfolio Growth Calculator - Track Total Nest Eggs',
    metaDesc: 'Simulate long-term asset expansion of multi-asset portfolios including initial balances and dynamic compound additions.',
    primaryKeyword: 'Portfolio Growth Calculator',
    formulaName: 'Multi-Asset Growth Modeling',
    formulaDesc: 'A = P × (1+r)^t + PMT × [((1+r)^t - 1)/r]',
    explanation: 'Enables users to input a large existing portfolio base and overlay consistent systematic monthly allocations to determine long-term expansion timelines.',
    example: 'An existing $100,000 portfolio added with $1,000 monthly contributions grows to $751,200 in 15 years at a 9% return.',
    relatedSlugs: ['compound-interest', 'investment-goal', 'asset-allocation'],
    fields: [
      { key: 'currentValue', label: 'Starting Portfolio Value', type: 'number', defaultValue: 100000, isCurrency: true },
      { key: 'monthlySave', label: 'Systematic Monthly Addition', type: 'number', defaultValue: 1000, isCurrency: true },
      { key: 'rate', label: 'Portfolio Blended Return (%)', type: 'number', defaultValue: 9, isPercent: true },
      { key: 'years', label: 'Timeline (Years)', type: 'number', defaultValue: 15, min: 1, max: 40 }
    ],
    faqs: [
      { question: 'What is a blended return rate?', answer: 'The combined weighted return rate of your diverse asset buckets (e.g. 70% equities yielding 11% + 30% bonds yielding 6% = 9.5% blended return).' },
      { question: 'How often should portfolio targets be checked?', answer: 'Revisit your allocations and balances bi-annually or annually to adjust for market swings and personal target changes.' }
    ],
    calculate: (inputs, currency) => {
      const p = inputs.currentValue || 0;
      const pmt = inputs.monthlySave || 0;
      const r = (inputs.rate || 9) / 100 / 12;
      const t = inputs.years || 15;
      let balance = p;
      let contributions = p;
      const chartData = [];
      for (let y = 1; y <= t; y++) {
        for (let m = 0; m < 12; m++) {
          balance = balance * (1 + r) + pmt;
          contributions += pmt;
        }
        chartData.push({
          year: `Yr ${y}`,
          balance: Math.round(balance),
          contributions: Math.round(contributions)
        });
      }
      return {
        metrics: [
          { label: 'Projected Portfolio Value', value: balance, isPrimary: true, desc: 'Accumulated compound balance' },
          { label: 'Out-of-Pocket Cost', value: contributions, desc: 'Your starting principal + savings' },
          { label: 'Earned Compound Wealth', value: Math.max(0, balance - contributions), desc: 'Returns generated by markets' }
        ],
        chartData,
        explanationText: `Your starting base of ${p.toLocaleString()} paired with systematic monthly saves of ${pmt.toLocaleString()} compiles into a secure nest egg of ${Math.round(balance).toLocaleString()} in ${t} years.`
      };
    }
  };
